
spring:
  application:
    name: notification-service
  # configuration for rabbit MQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoint:
    web:
      exposure:
        include: '*'

server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

#rabbit mq configuration setup
rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking
